spring:	
	profiles:	
	active:	
	- dev
---
spring:	
	profiles:	dev     #
	application:	
	name:	microservicecloud-config-atguigu-dev
---
spring:	
	profiles:	test     #Ի
	application:	
	name:	microservicecloud-config-atguigu-test

#뱣Ϊutf-8ʽ
 
